# Port Scan Detection Report

## Project Information

**Project:** Port Scan Detection

**Environment:** VMware Virtual Lab

**Attacker:** Kali Linux

**Target:** Ubuntu Server

**Target IP:** 192.168.81.129

**Tools:** Nmap, Wireshark, Apache2, OpenSSH

---

# Objective

The objective of this project is to detect and analyze TCP port scanning activity using Wireshark while generating reconnaissance traffic with Nmap.

---

# Lab Preparation

The Ubuntu target was updated and configured with Apache2 and OpenSSH services.

The Kali attacker machine was updated and verified with Nmap installed.

Wireshark was launched on the Ubuntu machine to capture all incoming traffic during the scans.

---

# Scan Types Performed

- Default Scan
- SYN Scan
- Version Detection (-sV)
- OS Detection (-O)
- Aggressive Scan (-A)

---

# Wireshark Analysis

The captured traffic was analyzed using:

- Capture File Properties
- Protocol Hierarchy
- Conversations
- Endpoints

The following filters were applied:

- tcp
- tcp.flags.syn == 1 && tcp.flags.ack == 0
- tcp.flags.syn == 1 && tcp.flags.ack == 1
- tcp.flags.reset == 1
- tcp.port == 22
- tcp.port == 80

---

# Findings

- More than 11,000 packets captured.
- TCP accounted for 98.3% of all traffic.
- More than 5,100 SYN packets detected.
- More than 5,100 RST packets detected.
- Only ports 22 and 80 were open.
- Sequential SYN packets confirmed automated reconnaissance activity.

---

# Indicators of Compromise (IOCs)

**Source IP**

192.168.81.128

**Target IP**

192.168.81.129

**Open Ports**

- 22 (SSH)
- 80 (HTTP)

**Indicators**

- High number of SYN packets
- Large number of TCP Reset packets
- Sequential destination ports
- Very short intervals between packets

---

# Conclusion

The packet capture clearly demonstrates an automated TCP port scan generated by Nmap. Wireshark analysis confirmed thousands of SYN packets targeting multiple ports, with only SSH and HTTP responding successfully. The observed traffic pattern is consistent with reconnaissance activity typically detected by SOC analysts.

---

# Skills Demonstrated

- Network Traffic Analysis
- Port Scan Detection
- Wireshark Packet Analysis
- Nmap Scanning
- TCP Analysis
- SOC Investigation
